### ISSUE TITLE
It is not possible to download the files of the onnx models

### ISSUE THREAD

**Issue by livingbeams** [asiryan/FaceONNX#1]
Trying to clone de repository it gives a quota error for the files referenced with github LFS.

Could it be possible to upload the model files to some other storage such us Google Drive or some other?

Regards

**Comment by asiryan** [comment]
Thank you for your comment. I removed git-lfs from FaceONNX repo. Now models are available on [google.drive](https://drive.google.com/drive/folders/1gh1E0yWqgzRX3Cxsp_EtZ2BAVOxyVAPb?usp=sharing).
