### ISSUE TITLE
FaceONNX.Addons.Gpu runtime exception

### ISSUE THREAD

**Issue by coder39248583** [asiryan/FaceONNX#3]
FaceONNX.Gpu works great, but when I add the nuget package FaceONNX.Addons.Gpu, the following code throws a runtime exception:
```c#
var genderDetector = new FaceGenderClassifier()
// System.Resources.MissingManifestResourceException: 
// 'Could not find any resources appropriate for the specified culture or the neutral culture.  
// Make sure "FaceONNX.Gpu.Addons.Properties.Resources.resources" was correctly embedded or 
// linked into assembly "FaceONNX.Addons" at compile time, or that all the satellite 
// assemblies required are loadable and fully signed.'
```
I apologize if I'm missing something simple, but I can't figure it out.

My environment:
Win7-x64
Visual Studio 2019
WinForm .NET Framework 4.7.2

**Comment by asiryan** [comment]
Thank you, for your feedback!
I will fix it as soon as possible.

**Comment by asiryan** [comment]
> FaceONNX.Gpu works great, but when I add the nuget package FaceONNX.Addons.Gpu, the following code throws a runtime exception:
> 
> ```cs
> var genderDetector = new FaceGenderClassifier()
> // System.Resources.MissingManifestResourceException: 
> // 'Could not find any resources appropriate for the specified culture or the neutral culture.  
> // Make sure "FaceONNX.Gpu.Addons.Properties.Resources.resources" was correctly embedded or 
> // linked into assembly "FaceONNX.Addons" at compile time, or that all the satellite 
> // assemblies required are loadable and fully signed.'
> ```
> 
> I apologize if I'm missing something simple, but I can't figure it out.
> 
> My environment:
> Win7-x64
> Visual Studio 2019
> WinForm .NET Framework 4.7.2

Please, install FaceONNX.Addons.Gpu 1.5.0.3
```
https://www.nuget.org/packages/FaceONNX.Addons.Gpu/1.0.5.3
```
